# fly.toml app configuration file generated for capomedia on 2023-09-18T23:01:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "capomedia"
primary_region = "lax"

[build]

[deploy]
  release_command = ".fly/release.sh"

[env]
  DATABASE_URL = "file://data/sqlite.db"
  MIGRATE_ON_BOOT = "true"
  PORT = "8910"
  REDWOOD_DISABLE_TELEMETRY = "1"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
